// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dnxpBTDaNBSNN5x6ghTdfE
// Component: P3t1ysdnlIc
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: yL8Oej7_xqX/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_todo_mvc.module.css"; // plasmic-import: dnxpBTDaNBSNN5x6ghTdfE/projectcss
import * as sty from "./PlasmicTask.module.css"; // plasmic-import: P3t1ysdnlIc/css

export type PlasmicTask__VariantMembers = {
  state: "checked" | "editing";
};

export type PlasmicTask__VariantsArgs = {
  state?: SingleChoiceArg<"checked" | "editing">;
};

type VariantPropType = keyof PlasmicTask__VariantsArgs;
export const PlasmicTask__VariantProps = new Array<VariantPropType>("state");

export type PlasmicTask__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicTask__ArgsType;
export const PlasmicTask__ArgProps = new Array<ArgPropType>("children");

export type PlasmicTask__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  textbox?: p.Flex<"input">;
  button?: p.Flex<"button">;
};

export interface DefaultTaskProps {
  children?: React.ReactNode;
  state?: SingleChoiceArg<"checked" | "editing">;
  className?: string;
}

function PlasmicTask__RenderFunc(props: {
  variants: PlasmicTask__VariantsArgs;
  args: PlasmicTask__ArgsType;
  overrides: PlasmicTask__OverridesType;
  dataFetches?: PlasmicTask__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    theme: useTheme()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__global_theme_dark]: hasVariant(
          globalVariants,
          "theme",
          "dark"
        ),
        [sty.root__state_checked]: hasVariant(variants, "state", "checked"),
        [sty.root__state_editing]: hasVariant(variants, "state", "editing"),
        [sty.root__state_editing_global_theme_dark]:
          hasVariant(variants, "state", "editing") &&
          hasVariant(globalVariants, "theme", "dark")
      })}
    >
      <div
        className={classNames(defaultcss.all, sty.freeBox__dO6O3, {
          [sty.freeBox__state_editing__dO6O3NAujU]: hasVariant(
            variants,
            "state",
            "editing"
          ),
          [sty.freeBox__state_editing_global_theme_dark__dO6O3NAujUP75X]:
            hasVariant(variants, "state", "editing") &&
            hasVariant(globalVariants, "theme", "dark")
        })}
      >
        {(hasVariant(variants, "state", "editing") ? false : true) ? (
          <div
            className={classNames(defaultcss.all, sty.freeBox__vcYQd, {
              [sty.freeBox__state_checked__vcYQd88HzY]: hasVariant(
                variants,
                "state",
                "checked"
              ),
              [sty.freeBox__state_checked_global_theme_dark__vcYQd88HzYP75X]:
                hasVariant(variants, "state", "checked") &&
                hasVariant(globalVariants, "theme", "dark"),
              [sty.freeBox__state_editing__vcYQdnAujU]: hasVariant(
                variants,
                "state",
                "editing"
              )
            })}
          >
            {(hasVariant(variants, "state", "checked") ? true : false) ? (
              <p.PlasmicImg
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img, {
                  [sty.img__state_checked]: hasVariant(
                    variants,
                    "state",
                    "checked"
                  ),
                  [sty.img__state_checked_global_theme_dark]:
                    hasVariant(variants, "state", "checked") &&
                    hasVariant(globalVariants, "theme", "dark"),
                  [sty.img__state_editing]: hasVariant(
                    variants,
                    "state",
                    "editing"
                  )
                })}
                displayHeight={
                  hasVariant(variants, "state", "checked")
                    ? ("23px" as const)
                    : ("16px" as const)
                }
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(variants, "state", "checked")
                    ? ("23px" as const)
                    : ("16px" as const)
                }
                src={
                  hasVariant(variants, "state", "checked")
                    ? ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3Ryb2tlLXdpZHRoPSIwIiBmaWxsPSJjdXJyZW50Q29sb3IiIHN0cm9rZT0iY3VycmVudENvbG9yIiBzdHlsZT0iZmlsbDogcmdiKDQsIDE0MywgNjQpOyI+PHBhdGggZD0iTTE3My44OTggNDM5LjQwNGwtMTY2LjQtMTY2LjRjLTkuOTk3LTkuOTk3LTkuOTk3LTI2LjIwNiAwLTM2LjIwNGwzNi4yMDMtMzYuMjA0YzkuOTk3LTkuOTk4IDI2LjIwNy05Ljk5OCAzNi4yMDQgMEwxOTIgMzEyLjY5IDQzMi4wOTUgNzIuNTk2YzkuOTk3LTkuOTk3IDI2LjIwNy05Ljk5NyAzNi4yMDQgMGwzNi4yMDMgMzYuMjA0YzkuOTk3IDkuOTk3IDkuOTk3IDI2LjIwNiAwIDM2LjIwNGwtMjk0LjQgMjk0LjQwMWMtOS45OTggOS45OTctMjYuMjA3IDkuOTk3LTM2LjIwNC0uMDAxeiIvPjwvc3ZnPg==" as const)
                    : ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3Ryb2tlLXdpZHRoPSIwIiBmaWxsPSJjdXJyZW50Q29sb3IiIHN0cm9rZT0iY3VycmVudENvbG9yIj48cGF0aCBkPSJNMTczLjg5OCA0MzkuNDA0bC0xNjYuNC0xNjYuNGMtOS45OTctOS45OTctOS45OTctMjYuMjA2IDAtMzYuMjA0bDM2LjIwMy0zNi4yMDRjOS45OTctOS45OTggMjYuMjA3LTkuOTk4IDM2LjIwNCAwTDE5MiAzMTIuNjkgNDMyLjA5NSA3Mi41OTZjOS45OTctOS45OTcgMjYuMjA3LTkuOTk3IDM2LjIwNCAwbDM2LjIwMyAzNi4yMDRjOS45OTcgOS45OTcgOS45OTcgMjYuMjA2IDAgMzYuMjA0bC0yOTQuNCAyOTQuNDAxYy05Ljk5OCA5Ljk5Ny0yNi4yMDcgOS45OTctMzYuMjA0LS4wMDF6Ii8+PC9zdmc+" as const)
                }
              />
            ) : null}
          </div>
        ) : null}
      </div>

      <div
        className={classNames(defaultcss.all, sty.freeBox__mNve, {
          [sty.freeBox__global_theme_dark__mNvEp75X]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),
          [sty.freeBox__state_editing__mNvEnAujU]: hasVariant(
            variants,
            "state",
            "editing"
          ),
          [sty.freeBox__state_editing_global_theme_dark__mNvEnAujUP75X]:
            hasVariant(variants, "state", "editing") &&
            hasVariant(globalVariants, "theme", "dark")
        })}
      >
        {(hasVariant(variants, "state", "editing") ? false : true) ? (
          <div
            className={classNames(defaultcss.all, sty.freeBox__dD456, {
              [sty.freeBox__state_checked__dD45688HzY]: hasVariant(
                variants,
                "state",
                "checked"
              ),
              [sty.freeBox__state_editing__dD456NAujU]: hasVariant(
                variants,
                "state",
                "editing"
              )
            })}
          >
            {p.renderPlasmicSlot({
              defaultContents: "Some kind of text here",
              value: args.children,
              className: classNames(sty.slotTargetChildren, {
                [sty.slotTargetChildren__global_theme_dark]: hasVariant(
                  globalVariants,
                  "theme",
                  "dark"
                ),
                [sty.slotTargetChildren__state_checked]: hasVariant(
                  variants,
                  "state",
                  "checked"
                ),
                [sty.slotTargetChildren__state_checked_global_theme_dark]:
                  hasVariant(variants, "state", "checked") &&
                  hasVariant(globalVariants, "theme", "dark"),
                [sty.slotTargetChildren__state_editing]: hasVariant(
                  variants,
                  "state",
                  "editing"
                )
              })
            })}
          </div>
        ) : null}
        {(hasVariant(variants, "state", "editing") ? true : false) ? (
          <input
            data-plasmic-name={"textbox"}
            data-plasmic-override={overrides.textbox}
            className={classNames(defaultcss.input, sty.textbox, {
              [sty.textbox__state_editing]: hasVariant(
                variants,
                "state",
                "editing"
              ),
              [sty.textbox__state_editing_global_theme_dark]:
                hasVariant(variants, "state", "editing") &&
                hasVariant(globalVariants, "theme", "dark")
            })}
            placeholder={"Some placeholder text" as const}
            type={"text" as const}
          />
        ) : null}
        {(hasVariant(variants, "state", "editing") ? false : true) ? (
          <div
            className={classNames(defaultcss.all, sty.freeBox__hgukj, {
              [sty.freeBox__state_editing__hgukjnAujU]: hasVariant(
                variants,
                "state",
                "editing"
              )
            })}
          >
            <button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames(
                defaultcss.button,
                defaultcss.__wab_text,
                sty.button,
                {
                  [sty.button__state_editing]: hasVariant(
                    variants,
                    "state",
                    "editing"
                  )
                }
              )}
            >
              {"×"}
            </button>
          </div>
        ) : null}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "textbox", "button"],
  img: ["img"],
  textbox: ["textbox"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof p.PlasmicImg;
  textbox: "input";
  button: "button";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTask__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTask__VariantsArgs;
    args?: PlasmicTask__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTask__Fetches;
  } & Omit<PlasmicTask__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTask__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTask__ArgProps,
      internalVariantPropNames: PlasmicTask__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTask__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTask";
  } else {
    func.displayName = `PlasmicTask.${nodeName}`;
  }
  return func;
}

export const PlasmicTask = Object.assign(
  // Top-level PlasmicTask renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    textbox: makeNodeComponent("textbox"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicTask
    internalVariantProps: PlasmicTask__VariantProps,
    internalArgProps: PlasmicTask__ArgProps
  }
);

export default PlasmicTask;
/* prettier-ignore-end */
