// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dnxpBTDaNBSNN5x6ghTdfE
// Component: GoA4NafDjvA
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_todo_mvc.module.css"; // plasmic-import: dnxpBTDaNBSNN5x6ghTdfE/projectcss
import * as sty from "./PlasmicToggleButton.module.css"; // plasmic-import: GoA4NafDjvA/css

export type PlasmicToggleButton__VariantMembers = {
  state: "selected";
};

export type PlasmicToggleButton__VariantsArgs = {
  state?: SingleChoiceArg<"selected">;
};

type VariantPropType = keyof PlasmicToggleButton__VariantsArgs;
export const PlasmicToggleButton__VariantProps = new Array<VariantPropType>(
  "state"
);

export type PlasmicToggleButton__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicToggleButton__ArgsType;
export const PlasmicToggleButton__ArgProps = new Array<ArgPropType>("children");

export type PlasmicToggleButton__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultToggleButtonProps {
  children?: React.ReactNode;
  state?: SingleChoiceArg<"selected">;
  className?: string;
}

function PlasmicToggleButton__RenderFunc(props: {
  variants: PlasmicToggleButton__VariantsArgs;
  args: PlasmicToggleButton__ArgsType;
  overrides: PlasmicToggleButton__OverridesType;
  dataFetches?: PlasmicToggleButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__state_selected]: hasVariant(variants, "state", "selected")
      })}
    >
      {p.renderPlasmicSlot({
        defaultContents: "All",
        value: args.children,
        className: classNames(sty.slotTargetChildren, {
          [sty.slotTargetChildren__state_selected]: hasVariant(
            variants,
            "state",
            "selected"
          )
        })
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicToggleButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicToggleButton__VariantsArgs;
    args?: PlasmicToggleButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicToggleButton__Fetches;
  } & Omit<PlasmicToggleButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicToggleButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicToggleButton__ArgProps,
      internalVariantPropNames: PlasmicToggleButton__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicToggleButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicToggleButton";
  } else {
    func.displayName = `PlasmicToggleButton.${nodeName}`;
  }
  return func;
}

export const PlasmicToggleButton = Object.assign(
  // Top-level PlasmicToggleButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicToggleButton
    internalVariantProps: PlasmicToggleButton__VariantProps,
    internalArgProps: PlasmicToggleButton__ArgProps
  }
);

export default PlasmicToggleButton;
/* prettier-ignore-end */
